server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.94:3306/mydb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: admin
    password: password

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true

mybatis:
  type-aliases-package: org.cloud.springcloud.entity
  mapper-locations: classpath*:mapper/*.xml